name: barikoi
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8

  fluttertoast: ^8.2.8
  dio: ^5.7.0
  shimmer: ^3.0.0
  intl: any
  provider: ^6.1.2
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.9.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.14
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  flutter_secure_storage: ^9.2.2
  freezed: ^2.5.7
  flutter_native_splash: ^2.4.2
  flutter_launcher_icons: ^0.14.1
  geolocator: ^13.0.1
  logger: ^2.4.0
  go_router: ^14.4.1
  location: ^7.0.1
  flutter_polyline_points: ^2.1.0
  maplibre_gl: ^0.20.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  build_runner: ^2.4.13

  json_serializable: ^6.8.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter_native_splash:
  image: "assets/images/splash_icon.png"
  color: "#FFFFFF"
  android_12:
    image: "assets/images/splash_icon.png"
    color: "#FFFFFF"
  android: true
  ios: true
  web: false


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svgImages/
    - assets/
    - assets/images/current_location.png
    - assets/images/source_location.png